global:
  postgresql:
    auth:
      postgresPassword: "pass"
      username: "postgres"
      password: "pass"
      database: "universitydb"
primary:
  persistence:
    enabled: true
    existingClaim: "postgres-pvc"
    # storageClass: "standard"
  initdb:
    user: "postgres"
    password: "pass"

securityContext:
  fsGroup: 1001
  runAsUser: 1001
