apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollments-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollments-app
  template:
    metadata:
      labels:
        app: enrollments-app
    spec:
      containers:
      - name: enrollments-app
        image: markvellaum/university:v0.0.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PGHOST
        - name: PGPORT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PGPORT
        - name: PGDB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PGDB
        - name: PGUSER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PGUSER
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /bitnami/postgresql
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: enrollments-app-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: enrollments-app
